# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.2.3
tutorial: false

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

countries: ["MA"]
# Can be replaced by country ["NG", "BJ"], continent ["Africa"] or user-specific region, see more at https://pypsa-earth.readthedocs.io/en/latest/configuration.html#top-level-configuration

enable:
  retrieve_databundle: true  #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_cost_data: true  # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: true  # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: true  # If True, than an exclusion raster will be build
  build_cutout: false
  # If "build_cutout" : true, then environmental data is extracted according to `snapshots` date range and `countries`
  # requires cds API key https://cds.climate.copernicus.eu/api-how-to
  # More information https://atlite.readthedocs.io/en/latest/introduction.html#datasets

custom_rules: []  # Default empty [] or link to custom rule file e.g. ["my_folder/my_rules.smk"] that add rules to Snakefile

run:
  name: "" # use this to keep track of runs with different settings
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
                        # Note: value false requires build_cutout to be enabled

scenario:
  simpl: ['']
  ll: ['1.0']
  clusters: [10]
  opts: [Co2L1-144H]

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: "left" # end is not inclusive

# definition of the Coordinate Reference Systems
crs:
  geo_crs: EPSG:4326  # general geographic projection, not used for metric measures. "EPSG:4326" is the standard used by OSM and google maps
  distance_crs: EPSG:3857  # projection for distance measurements only. Possible recommended values are "EPSG:3857" (used by OSM and Google Maps)
  area_crs: ESRI:54009  # projection for area measurements only. Possible recommended values are Global Mollweide "ESRI:54009"

# download_osm_data_nprocesses: 10  # (optional) number of threads used to download osm data

augmented_line_connection:
  add_to_snakefile: false
  connectivity_upgrade: 2
  min_DC_length: 600
  min_expansion: 1
  new_line_type:
  - HVAC
base_network:
  min_voltage_rebase_voltage: 35000
  min_voltage_substation_offshore: 35000
build_osm_network:
  force_ac: false
  group_close_buses: true
  group_tolerance_buses: 5000
  overpassing_lines_tolerance: 1
  split_overpassing_lines: true
build_shape_options:
  contended_flag: set_by_country
  gadm_layer_id: 1
  gdp_method: standard
  nchunks: 2
  nprocesses: 2
  out_logging: true
  update_file: false
  worldpop_method: standard
  year: 2020
clean_osm_data_options:
  add_line_endings: true
  generator_name_method: OSM
  names_by_shapes: true
  tag_substation: transmission
  threshold_voltage: 35000
cluster_options:
  simplify_network:
    to_substations: false # network is simplified to nodes with positive or negative power injection (i.e. substations or offwind connections)
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time # only for hac. choose from: [solar+onwind-time, solar+onwind-cap, solar-time, solar-cap, solar+offwind-cap] etc.
    exclude_carriers: []
    remove_stubs: true
    remove_stubs_across_borders: true
    p_threshold_drop_isolated: 20 # [MW] isolated buses are being discarded if bus mean power is below the specified threshold
    p_threshold_merge_isolated: 300 # [MW] isolated buses are being merged into a single isolated bus if bus mean power is below the specified threshold
  cluster_network:
    algorithm: kmeans
    feature: solar+onwind-time
    exclude_carriers: []
  alternative_clustering: true  # "False" use Voronoi shapes, "True" use GADM shapes
  distribute_cluster: ['load'] # Distributes cluster nodes per country according to ['load'],['pop'] or ['gdp']
  out_logging: true  # When "True", logging is printed to console
  aggregation_strategies:
    generators:
      committable: any
      efficiency: mean
      marginal_cost: mean
      p_min_pu: mean
      p_nom: sum
      p_nom_max: sum
      p_nom_min: sum
      ramp_limit_down: max
      efficiency: mean

build_shape_options:
  gadm_layer_id: 1  # GADM level area used for the gadm_shapes. Codes are country-dependent but roughly: 0: country, 1: region/county-like, 2: municipality-like
  update_file: false  # When true, all the input files are downloaded again and replace the existing files
  out_logging: true  # When true, logging is printed to console
  year: 2020  # reference year used to derive shapes, info on population and info on GDP
  nprocesses: 3  # number of processes to be used in build_shapes
  nchunks: 3  # number of data chuncks for build_shapes. If not specified or smaller than nprocesses, specified as nprocesses
  worldpop_method: "standard"  # "standard" pulls from web 1kmx1km raster, "api" pulls from API 100mx100m raster, false (not "false") no pop addition to shape which is useful when generating only cutout
  gdp_method: "standard"  # "standard" pulls from web 1x1km raster, false (not "false") no gdp addition to shape which useful when generating only cutout
  contended_flag: "set_by_country" # "set_by_country" assigns the contended areas to the countries according to the GADM database, "drop" drops these contended areas from the model

clean_osm_data_options:  # osm = OpenStreetMap
  names_by_shapes: true  # Set the country name based on the extended country shapes
  threshold_voltage: 51000  # [V] assets below that voltage threshold will not be used (cable, line, generator, etc.)
  tag_substation: "transmission"  # Filters only substations with 'transmission' tag, ('distribution' also available)
  add_line_endings: true  # When "True", then line endings are added to the dataset of the substations
  generator_name_method: OSM  # Methodology to specify the name to the generator. Options: OSM (name as by OSM dataset), closest_city (name by the closest city)
  use_custom_lines: "OSM_only"  # Use OSM (OSM_only), customized (custom_only), or both data sets (add_custom)
  path_custom_lines: false  # If exists, provide the specific absolute path of the custom file e.g. (...\data\custom_lines.geojson)
  use_custom_substations: "OSM_only"  # Use OSM (OSM_only), customized (custom_only), or both data sets (add_custom)
  path_custom_substations: false  # If exists, provide the specific absolute path of the custom file e.g. (...\data\custom_substations.geojson)
  use_custom_cables: "OSM_only"  # Use OSM (OSM_only), customized (custom_only), or both data sets (add_custom)
  path_custom_cables: false  # If exists, provide the specific absolute path of the custom file e.g. (...\data\custom_cables.geojson)

build_osm_network:  # Options of the build_osm_network script; osm = OpenStreetMap
  group_close_buses: true  # When "True", close buses are merged and guarantee the voltage matching among line endings
  group_tolerance_buses: 5000  # [m] (default 5000) Tolerance in meters of the close buses to merge
  split_overpassing_lines: true  # When True, lines overpassing buses are splitted and connected to the bueses
  overpassing_lines_tolerance: 1  # [m] (default 1) Tolerance to identify lines overpassing buses
  force_ac: false  # When true, it forces all components (lines and substation) to be AC-only. To be used if DC assets create problem.

base_network:
  min_voltage_substation_offshore: 51000  # [V] minimum voltage of the offshore substations
  min_voltage_rebase_voltage: 51000  # [V] minimum voltage in base network

load_options:
  ssp: "ssp2-2.6" # shared socio-economic pathway (GDP and population growth) scenario to consider
  weather_year: 2013  # Load scenarios available with different weather year (different renewable potentials)
  prediction_year: 2030  # Load scenarios available with different prediction year (GDP, population)
  scale: 1  # scales all load time-series, i.e. 2 = doubles load

electricity:
  agg_p_nom_limits: data/agg_p_nom_minmax.csv
  hvdc_as_lines: false  # should HVDC lines be modeled as `Line` or as `Link` component?
  automatic_emission: false
  automatic_emission_base_year: 1990 # 1990 is taken as default. Any year from 1970 to 2018 can be selected.

  operational_reserve: # like https://genxproject.github.io/GenX/dev/core/#Reserves
    activate: false
    epsilon_load: 0.02 # share of total load
    epsilon_vres: 0.02 # share of total renewable supply
    contingency: 0 # fixed capacity in MW

  max_hours:
    battery: 6
    H2: 168

  extendable_carriers:
    Generator:
    - solar
    - onwind
    - offwind-ac
    - offwind-dc
    - OCGT
    Link: []
    StorageUnit: []
    Store: []
  hvdc_as_lines: false
  max_hours:
    H2: 168
    battery: 6
  operational_reserve:
    activate: false
    contingency: 0
    epsilon_load: 0.02
    epsilon_vres: 0.02
  powerplants_filter: (DateOut >= 2022 or DateOut != DateOut)
  renewable_carriers:
  - solar
  - onwind
  - offwind-ac
  - offwind-dc
  - hydro
  voltages:
  - 220.0
  - 300.0
  - 380.0
enable:
  build_cutout: false
  build_natura_raster: true
  download_osm_data: true
  retrieve_cost_data: true
  retrieve_databundle: true
lines:
  dc_type: HVDC XLPE 1000
  length_factor: 1.25
  s_max_pu: 0.7
  s_nom_max: .inf
  types:
    220.0: Al/St 240/40 2-bundle 220.0
    300.0: Al/St 240/40 3-bundle 300.0
    380.0: Al/St 240/40 4-bundle 380.0
  under_construction: zero
links:
  p_max_pu: 1.0
  p_nom_max: .inf
  under_construction: zero
load_options:
  prediction_year: 2030
  scale: 1
  ssp: ssp2-2.6
  weather_year: 2013
logging:
  format: '%(levelname)s:%(name)s:%(message)s'
  level: INFO
monte_carlo:
  options:
    add_to_snakefile: false
    samples: 7
    sampling_strategy: chaospy
  pypsa_standard:
    loads_t.p_set:
    - 0.9
    - 1.1
plotting:
  AC_carriers:
  - AC line
  - AC transformer
  conv_techs:
  - OCGT
  - CCGT
  - nuclear
  - coal
  - oil
  costs_max: 800
  costs_threshold: 1
  energy_max: 15000.0
  energy_min: -10000.0
  energy_threshold: 50.0
  link_carriers:
  - DC line
  - Converter AC-DC
  load_carriers:
  - AC load
  map:
    boundaries:
    - -10.2
    - 29
    - 35
    - 72
    figsize:
    - 7
    - 7
    p_nom:
      bus_size_factor: 50000.0
      linewidth_factor: 3000.0
  nice_names:
    CCGT: Combined-Cycle Gas
    H2: Hydrogen Storage
    OCGT: Open-Cycle Gas
    PHS: Pumped Hydro Storage
    battery: Battery Storage
    hydro: Reservoir & Dam
    lines: Transmission Lines
    offwind-ac: Offshore Wind (AC)
    offwind-dc: Offshore Wind (DC)
    onwind: Onshore Wind
    ror: Run of River
    solar: Solar
  storage_techs:
  - hydro+PHS
  - battery
  - H2
  tech_colors:
    AC line: '#70af1d'
    AC-AC: '#70af1d'
    CCGT: '#b20101'
    DC link: '#8a1caf'
    DC-DC: '#8a1caf'
    Electric load: '#f9d002'
    H2: '#ea048a'
    HVDC links: '#8a1caf'
    OCGT: '#d35050'
    PHS: '#08ad97'
    battery: '#b8ea04'
    biogas: '#23932d'
    biomass: '#0c6013'
    coal: '#707070'
    electricity: '#f9d002'
    gas: '#d35050'
    geothermal: '#ba91b1'
    hydro: '#08ad97'
    hydro reservoir: '#08ad97'
    hydro+PHS: '#08ad97'
    hydroelectricity: '#08ad97'
    hydrogen storage: '#ea048a'
    lignite: '#9e5a01'
    lines: '#70af1d'
    links: '#8a1caf'
    load: '#FF0000'
    natural gas: '#d35050'
    nuclear: '#ff9000'
    offshore wind: '#6895dd'
    offshore wind ac: '#6895dd'
    offshore wind dc: '#74c6f2'
    offwind: '#6895dd'
    offwind-ac: '#6895dd'
    offwind-dc: '#74c6f2'
    oil: '#262626'
    onshore wind: '#235ebc'
    onwind: '#235ebc'
    ror: '#4adbc8'
    run of river: '#4adbc8'
    solar: '#f9d002'
    solar PV: '#f9d002'
    solar thermal: '#ffef60'
    solid biomass: '#06540d'
    transmission lines: '#70af1d'
    waste: '#68896b'
  vre_techs:
  - onwind
  - offwind-ac
  - offwind-dc
  - solar
  - ror
renewable:
  hydro:
    PHS_max_hours: 6
    carriers:
    - ror
    - PHS
    - hydro
    clip_min_inflow: 1.0
    cutout: cutout-2013-era5-tutorial
    hydro_max_hours: energy_capacity_totals_by_country
    hydro_max_hours_default: 6.0
    multiplier: 1.1
    normalization:
      method: hydro_capacities
      year: 2013
    resource:
      flowspeed: 1.0
      hydrobasins: data/hydrobasins/hybas_world_lev04_v1c.shp
      method: hydro
  offwind-ac:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    copernicus:
      grid_codes:
      - 80
      - 200
    cutout: cutout-2013-era5-tutorial
    extendable: true
    max_depth: 50
    max_shore_distance: 30000
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
  offwind-dc:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    copernicus:
      grid_codes:
      - 80
      - 200
    cutout: cutout-2013-era5-tutorial
    extendable: true
    max_depth: 50
    min_shore_distance: 30000
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
  onwind:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    copernicus:
      distance: 1000
      distance_grid_codes:
      - 50
      grid_codes:
      - 20
      - 30
      - 40
      - 60
      - 100
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
    cutout: cutout-2013-era5-tutorial
    extendable: true
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: Vestas_V112_3MW
  solar:
    capacity_per_sqkm: 4.6
    clip_p_max_pu: 0.01
    copernicus:
      grid_codes:
      - 20
      - 30
      - 40
      - 50
      - 60
      - 90
      - 100
    correction_factor: 0.854337
    cutout: cutout-2013-era5-tutorial
    extendable: true
    natura: true
    potential: simple
    resource:
      method: hydro
      hydrobasins: data/hydrobasins/hybas_world_lev06_v1c.shp
      flowspeed: 1.0  # m/s
      # weight_with_height: false
      # show_progress: true
    carriers: [ror, PHS, hydro]
    PHS_max_hours: 6
    hydro_max_hours: "energy_capacity_totals_by_country"  # not active
    hydro_max_hours_default: 6.0  # (optional, default 6) Default value of max_hours for hydro when NaN values are found
    clip_min_inflow: 1.0
    extendable: true
    normalization:
      method: hydro_capacities  # 'hydro_capacities' to rescale country hydro production by using hydro_capacities, 'eia' to rescale by eia data, false for no rescaling
      year: 2013  # (optional) year of statistics used to rescale the runoff time series. When not provided, the weather year of the snapshots is used
    multiplier: 1.1  # multiplier applied after the normalization of the hydro production; default 1.0

# TODO: Needs to be adjusted for Africa.
# Costs Configuration (Do not remove, needed for Sphynx documentation).
costs:
  year: 2030
  version: v0.5.0
  rooftop_share: 0.14  # based on the potentials, assuming  (0.1 kW/m2 and 10 m2/person)
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    CO2 intensity: 0
    discount rate: 0.15
  marginal_cost: # EUR/MWh
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    electrolysis: 0.
    fuel cell: 0.
    battery: 0.
    battery inverter: 0.
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 0.


monte_carlo:
  options:
    add_to_snakefile: false
    samples: 7    # number of optimizations
    sampling_strategy: "chaospy"    # "pydoe2", "chaospy", "scipy", packages that are supported
  pypsa_standard:
      # User can add here flexibly more features for the Monte-Carlo sampling.
      # Given as "key: value" format
      # Key: add below the pypsa object for the monte_carlo sampling, "network" is only allowed for filtering!
      # Value: currently supported format [l_bound, u_bound] or empty [], represent multiplication factors for the object
    loads_t.p_set: [0.9, 1.1]
    # generators_t.p_max_pu.loc[:, n.generators.carrier == "wind"]: [0.9, 1.1]
    # generators_t.p_max_pu.loc[:, n.generators.carrier == "solar"]: [0.9, 1.1]


solving:
  options:
    clip_p_max_pu: 0.01
    formulation: kirchhoff
    load_shedding: true
    max_iterations: 6
    min_iterations: 4
    noisy_costs: true
    skip_iterations: true
    track_iterations: false
  solver:
    name: glpk
summary_dir: results
transformers:
  s_nom: 2000.0
  type: ''
  x: 0.1
tutorial: true
version: 0.2.2
