# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0
version: 0.5.0

run:
  name: NG  # Name of the configuration (arbitrary string value)
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
  base_config: config.tutorial.yaml  # base configuration file

countries:
- NG

scenario:
  clusters: [5]
