# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-earth
channels:
- bioconda
- gurobi
- https://conda.anaconda.org/gurobi
- conda-forge
- http://conda.anaconda.org/gurobi
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- affine=2.3.1
- alsa-lib=1.2.3.2
- amply=0.1.5
- anyio=3.6.1
- appdirs=1.4.4
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- asttokens=2.0.8
- atk-1.0=2.36.0
- attrs=22.1.0
- babel=2.10.3
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.4
- beautifulsoup4=4.11.1
- bleach=5.0.1
- blosc=1.21.1
- bokeh=2.4.3
- boost-cpp=1.74.0
- branca=0.5.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.6.15.1
- cairo=1.16.0
- cartopy=0.20.1
- certifi=2022.6.15.1
- cffi=1.15.1
- cfgv=3.3.1
- cfitsio=4.0.0
- cftime=1.6.1
- charset-normalizer=2.1.1
- click=8.1.3
- click-plugins=1.1.1
- cligj=0.7.2
- cloudpickle=2.2.0
- coin-or-cbc=2.10.8
- coin-or-cgl=0.60.6
- coin-or-clp=1.17.7
- coin-or-osi=0.108.7
- coin-or-utils=2.11.6
- coincbc=2.10.8
- colorama=0.4.5
- colorcet=3.0.0
- conda=4.14.0
- conda-package-handling=1.8.1
- configargparse=1.5.3
- connection_pool=0.0.3
- contextily=1.2.0
- country_converter=0.7.7
- cryptography=37.0.4
- curl=7.83.1
- cycler=0.11.0
- cytoolz=0.12.0
- dask=2022.9.0
- dask-core=2022.9.0
- datashader=0.14.2
- datashape=0.5.4
- datrie=0.8.2
- dbus=1.13.6
- debugpy=1.6.3
- decorator=5.1.1
- defusedxml=0.7.1
- descartes=1.1.0
- distlib=0.3.5
- distributed=2022.9.0
- docutils=0.19
- dpath=2.0.6
- entrypoints=0.4
- et_xmlfile=1.0.1
- executing=1.0.0
- expat=2.4.8
- filelock=3.8.0
- fiona=1.8.20
- flit-core=3.7.1
- folium=0.12.1.post1
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.37.1
- freetype=2.12.1
- freexl=1.0.6
- fribidi=1.0.10
- fsspec=2022.8.2
- future=0.18.2
- gdal=3.3.3
- gdk-pixbuf=2.42.8
- geographiclib=1.52
- geopandas=0.11.1
- geopandas-base=0.11.1
- geopy=2.2.0
- geos=3.10.0
- geotiff=1.7.0
- geoviews=1.9.5
- geoviews-core=1.9.5
- gettext=0.19.8.1
- giflib=5.2.1
- gitdb=4.0.9
- gitpython=3.1.27
- glpk=5.0
- gmp=6.2.1
- graphite2=1.3.13
- graphviz=2.50.0
- gst-plugins-base=1.18.5
- gstreamer=1.18.5
- gtk2=2.24.33
- gts=0.7.6
- gurobi=9.5.2
- harfbuzz=3.1.1
- hdf4=4.2.15
- hdf5=1.12.1
- heapdict=1.0.1
- holoviews=1.15.0
- hvplot=0.8.1
- icu=68.2
- identify=2.5.5
- idna=3.3
- importlib-metadata=4.11.4
- importlib_metadata=4.11.4
- importlib_resources=5.9.0
- ipopt=3.13.2
- ipykernel=6.15.2
- ipython=8.5.0
- ipython_genutils=0.2.0
- jedi=0.18.1
- jinja2=3.1.2
- joblib=1.1.0
- jpeg=9e
- json-c=0.15
- json5=0.9.5
- jsonschema=4.16.0
- jupyter_client=7.3.4
- jupyter_core=4.11.1
- jupyter_server=1.18.1
- jupyterlab=3.4.6
- jupyterlab_pygments=0.2.2
- jupyterlab_server=2.15.1
- kealib=1.4.15
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.19.3
- lcms2=2.12
- ld_impl_linux-64=2.36.1
- lerc=4.0.0
- libarchive=3.5.2
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libclang=11.1.0
- libcurl=7.83.1
- libdap4=3.20.6
- libdeflate=1.13
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libffi=3.4.2
- libgcc-ng=12.1.0
- libgd=2.3.3
- libgdal=3.3.3
- libgfortran-ng=12.1.0
- libgfortran5=12.1.0
- libglib=2.72.1
- libgomp=12.1.0
- libiconv=1.16
- libkml=1.3.0
- liblapack=3.9.0
- liblapacke=3.9.0
- libllvm10=10.0.1
- libllvm11=11.1.0
- libmamba=0.25.0
- libmambapy=0.25.0
- libnetcdf=4.8.1
- libnghttp2=1.47.0
- libnsl=2.0.0
- libogg=1.3.4
- libopenblas=0.3.21
- libopus=1.3.1
- libpng=1.6.37
- libpq=13.5
- librsvg=2.52.5
- librttopo=1.1.0
- libsodium=1.0.18
- libsolv=0.7.22
- libspatialindex=1.9.3
- libspatialite=5.0.1
- libsqlite=3.39.3
- libssh2=1.10.0
- libstdcxx-ng=12.1.0
- libtiff=4.4.0
- libtool=2.4.6
- libuuid=2.32.1
- libvorbis=1.3.7
- libwebp=1.2.4
- libwebp-base=1.2.4
- libxcb=1.13
- libxkbcommon=1.0.3
- libxml2=2.9.12
- libxslt=1.1.33
- libzip=1.9.2
- libzlib=1.2.12
- llvmlite=0.36.0
- locket=1.0.0
- lxml=4.8.0
- lz4=4.0.0
- lz4-c=1.9.3
- lzo=2.10
- mamba=0.25.0
- mapclassify=2.4.3
- markdown=3.4.1
- markupsafe=2.1.1
- matplotlib=3.5.3
- matplotlib-base=3.5.3
- matplotlib-inline=0.1.6
- memory_profiler=0.60.0
- mercantile=1.2.1
- metis=5.1.0
- mistune=2.0.4
- msgpack-python=1.0.4
- multipledispatch=0.6.0
- munch=2.5.0
- munkres=1.1.4
- mysql-common=8.0.30
- mysql-libs=8.0.30
- nbclassic=0.4.3
- nbclient=0.6.8
- nbconvert=7.0.0
- nbconvert-core=7.0.0
- nbconvert-pandoc=7.0.0
- nbformat=5.4.0
- ncurses=6.3
- nest-asyncio=1.5.5
- netcdf4=1.6.0
- networkx=2.8.6
- nodeenv=1.7.0
- nomkl=1.0
- notebook=6.4.12
- notebook-shim=0.1.0
- nspr=4.32
- nss=3.78
- numba=0.53.1
- numexpr=2.8.3
- numpy=1.23.2
- openjpeg=2.4.0
- openpyxl=3.0.10
- openssl=1.1.1q
- packaging=21.3
- pandas=1.4.4
- pandoc=2.19.2
- pandocfilters=1.5.0
- panel=0.13.1
- pango=1.48.10
- param=1.12.2
- parso=0.8.3
- partd=1.3.0
- patsy=0.5.2
- pcre=8.45
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.2.0
- pip=22.2.2
- pixman=0.40.0
- pkgutil-resolve-name=1.3.10
- plac=1.3.5
- platformdirs=2.5.2
- ply=3.11
- poppler=21.09.0
- poppler-data=0.4.11
- postgresql=13.5
- pre-commit=2.20.0
- proj=8.1.1
- prometheus_client=0.14.1
- prompt-toolkit=3.0.31
- psutil=5.9.2
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulp=2.6.0
- pure_eval=0.2.2
- py=1.11.0
- pybind11-abi=4
- pycosat=0.6.3
- pycountry=20.7.3
- pycparser=2.21
- pyct=0.4.6
- pyct-core=0.4.6
- pygments=2.13.0
- pyomo=6.4.2
- pyopenssl=22.0.0
- pyparsing=3.0.9
- pyproj=3.2.1
- pyqt=5.12.3
- pyqt-impl=5.12.3
- pyqt5-sip=4.19.18
- pyqtchart=5.12
- pyqtwebengine=5.12.1
- pyrsistent=0.18.1
- pyshp=2.3.1
- pysocks=1.7.1
- pytables=3.7.0
- python=3.9.13
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.1
- python_abi=3.9
- pytz=2022.2.1
- pyviz_comms=2.2.1
- pyyaml=6.0
- pyzmq=23.2.1
- qt=5.12.9
- rasterio=1.2.9
- ratelimiter=1.2.0
- readline=8.1.2
- reproc=14.2.3
- reproc-cpp=14.2.3
- requests=2.28.1
- retry=0.9.2
- reverse-geocode=1.4.1
- rioxarray=0.12.0
- rtree=1.0.0
- ruamel_yaml=0.15.80
- scikit-learn=1.1.2
- scipy=1.9.1
- seaborn=0.12.0
- seaborn-base=0.12.0
- send2trash=1.8.0
- setuptools=65.3.0
- shapely=1.8.0
- six=1.16.0
- smart_open=6.1.0
- smmap=3.0.5
- snakemake-minimal=7.14.0
- snappy=1.1.9
- sniffio=1.3.0
- snuggs=1.4.7
- sortedcontainers=2.4.0
- soupsieve=2.3.2.post1
- sqlite=3.39.3
- stack_data=0.5.0
- statsmodels=0.13.2
- stopit=1.1.2
- tabulate=0.8.10
- tblib=1.7.0
- terminado=0.15.0
- threadpoolctl=3.1.0
- tiledb=2.3.4
- tinycss2=1.1.1
- tk=8.6.12
- toml=0.10.2
- toolz=0.12.0
- toposort=1.7
- tornado=6.1
- tqdm=4.64.1
- traitlets=5.3.0
- typing_extensions=4.3.0
- tzcode=2022c
- tzdata=2022c
- ukkonen=1.0.1
- unicodedata2=14.0.0
- urllib3=1.26.11
- virtualenv=20.16.5
- wcwidth=0.2.5
- webencodings=0.5.1
- websocket-client=1.4.1
- wheel=0.37.1
- wrapt=1.14.1
- xarray=2022.6.0
- xerces-c=3.2.3
- xlrd=2.0.1
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2022.6.0
- xz=5.2.6
- yaml=0.2.5
- yaml-cpp=0.7.0
- yte=1.5.1
- zeromq=4.3.4
- zict=2.2.0
- zipp=3.8.1
- zlib=1.2.12
- zstd=1.5.2
- pip:
  - atlite==0.2.6.dev169+gcfcfd8b
  - bottleneck==1.3.5
  - cdsapi==0.5.1
  - countrycode==0.2
  - deprecation==2.1.0
  - entsoe-py==0.5.8
  - esy-osm-pbf==0.0.1
  - esy-osmfilter==1.0.11
  - googledrivedownloader==0.4
  - powerplantmatching==0.5.3
  - progressbar2==4.0.0
  - protobuf==3.20.1
  - pypsa==0.20.0
  - python-utils==3.3.3
  - tsam==2.1.0
  - unidecode==1.3.4
  - vresutils==0.3.1
prefix: /home/davidef/miniconda3/envs/pypsa-earth
