# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-earth-docs
channels:
- conda-forge/label/shapely_dev
- conda-forge
- bioconda
- http://conda.anaconda.org/gurobi
dependencies:
- python>=3.8
- pip
- mamba   # esp for windows build

- pypsa>=0.17.1
- atlite>=0.2.4
- dask<=2021.3.1   # until https://github.com/dask/dask/issues/7583 is solved
- earth-osm==0.0.8  # until 0.1.0

  # Dependencies of the workflow itself
- xlrd
- openpyxl
- pycountry
- seaborn
- snakemake-minimal
- memory_profiler
- yaml
- pytables
- lxml
- powerplantmatching>=0.4.8
- numpy
- pandas
- geopandas
  # - xarray  # till the main is not in conda- xarray
- netcdf4
- networkx
- scipy
- pydoe2
- shapely>=1.8a1
- progressbar2
- pyomo
- matplotlib

  # Keep in conda environment when calling ipython
- ipython

  # GIS dependencies:
- cartopy
- descartes
- rasterio
- geoviews
- hvplot

  # PyPSA-Eur-Sec Dependencies
- geopy
- tqdm
- pytz
- country_converter

- pip:
  - git+https://github.com/pydata/xarray@main   # till the main is not in conda
  - git+https://github.com/pypsa/pypsa.git#egg=pypsa
  - vresutils==0.3.1
  - tsam>=1.1.0
  - chaospy  # lastest version only available on pip
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx_link
  - gitpython
