# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-earth
channels:
- bioconda
- gurobi
- anaconda
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- affine=2.4.0
- aiofiles=22.1.0
- aiosqlite=0.19.0
- alsa-lib=1.2.8
- amply=0.1.5
- anyio=3.6.2
- appdirs=1.4.4
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- arrow-cpp=11.0.0
- asttokens=2.2.1
- atk-1.0=2.38.0
- atlite=0.2.11
- attr=2.5.1
- attrs=23.1.0
- aws-c-auth=0.6.26
- aws-c-cal=0.5.26
- aws-c-common=0.8.17
- aws-c-compression=0.2.16
- aws-c-event-stream=0.2.20
- aws-c-http=0.7.7
- aws-c-io=0.13.21
- aws-c-mqtt=0.8.6
- aws-c-s3=0.2.8
- aws-c-sdkutils=0.1.9
- aws-checksums=0.1.14
- aws-crt-cpp=0.19.9
- aws-sdk-cpp=1.10.57
- babel=2.12.1
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.4
- beautifulsoup4=4.12.2
- bleach=6.0.0
- blosc=1.21.3
- bokeh=2.4.3
- boltons=23.0.0
- boost-cpp=1.78.0
- bottleneck=1.3.7
- branca=0.6.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- c-blosc2=2.8.0
- ca-certificates=2023.01.10
- cairo=1.16.0
- cartopy=0.21.1
- cdsapi=0.6.1
- certifi=2022.12.7
- cffi=1.15.1
- cfgv=3.3.1
- cfitsio=4.2.0
- cftime=1.6.2
- charset-normalizer=3.1.0
- click=8.1.3
- click-plugins=1.1.1
- cligj=0.7.2
- cloudpickle=2.2.1
- coin-or-cbc=2.10.10
- coin-or-cgl=0.60.7
- coin-or-clp=1.17.8
- coin-or-osi=0.108.8
- coin-or-utils=2.11.9
- coincbc=2.10.10
- colorama=0.4.6
- colorcet=3.0.1
- comm=0.1.3
- conda=23.3.1
- conda-package-handling=2.0.2
- conda-package-streaming=0.7.0
- configargparse=1.5.3
- connection_pool=0.0.3
- contextily=1.3.0
- country_converter=1.0.0
- cryptography=40.0.2
- curl=8.0.1
- cycler=0.11.0
- cytoolz=0.12.0
- dask=2023.4.1
- dask-core=2023.4.1
- datashader=0.14.4
- datashape=0.5.4
- datrie=0.8.2
- dbus=1.13.6
- debugpy=1.6.7
- decorator=5.1.1
- defusedxml=0.7.1
- deprecation=2.1.0
- descartes=1.1.0
- distlib=0.3.6
- distributed=2023.4.1
- docutils=0.19
- dpath=2.1.5
- earth-osm=0.1.0
- entrypoints=0.4
- entsoe-py=0.5.8
- et_xmlfile=1.1.0
- exceptiongroup=1.1.1
- executing=1.2.0
- expat=2.5.0
- filelock=3.12.0
- fiona=1.9.3
- flit-core=3.8.0
- fmt=9.1.0
- folium=0.14.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.39.3
- freetype=2.12.1
- freexl=1.0.6
- fribidi=1.0.10
- fsspec=2023.4.0
- future=0.18.3
- gdal=3.6.4
- gdk-pixbuf=2.42.10
- geographiclib=1.52
- geojson-rewind=1.0.2
- geopandas=0.13.0
- geopandas-base=0.13.0
- geopy=2.3.0
- geos=3.11.2
- geotiff=1.7.1
- geoviews=1.9.6
- geoviews-core=1.9.6
- gettext=0.21.1
- gflags=2.2.2
- giflib=5.2.1
- gitdb=4.0.10
- gitpython=3.1.31
- glib=2.76.2
- glib-tools=2.76.2
- glog=0.6.0
- glpk=5.0
- gmp=6.2.1
- graphite2=1.3.13
- graphviz=8.0.5
- gst-plugins-base=1.22.0
- gstreamer=1.22.0
- gtk2=2.24.33
- gts=0.7.6
- gurobi=10.0.1
- harfbuzz=6.0.0
- hdf4=4.2.15
- hdf5=1.14.0
- holoviews=1.15.4
- humanfriendly=10.0
- hvplot=0.8.3
- icu=72.1
- identify=2.5.24
- idna=3.4
- importlib-metadata=6.6.0
- importlib_metadata=6.6.0
- importlib_resources=5.12.0
- iniconfig=2.0.0
- ipopt=3.13.2
- ipykernel=6.22.0
- ipython=8.13.2
- ipython_genutils=0.2.0
- jedi=0.18.2
- jinja2=3.1.2
- joblib=1.2.0
- json-c=0.16
- json5=0.9.5
- jsonpatch=1.32
- jsonpointer=2.0
- jsonschema=4.17.3
- jupyter_client=8.2.0
- jupyter_core=5.3.0
- jupyter_events=0.6.3
- jupyter_server=2.5.0
- jupyter_server_fileid=0.9.0
- jupyter_server_terminals=0.4.4
- jupyter_server_ydoc=0.8.0
- jupyter_ydoc=0.2.3
- jupyterlab=3.6.3
- jupyterlab_pygments=0.2.2
- jupyterlab_server=2.22.1
- kealib=1.5.0
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.20.1
- lame=3.100
- lcms2=2.15
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20230125.0
- libaec=1.0.6
- libarchive=3.6.2
- libarrow=11.0.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcap=2.67
- libcblas=3.9.0
- libclang=16.0.3
- libclang13=16.0.3
- libcrc32c=1.1.2
- libcups=2.3.3
- libcurl=8.0.1
- libdeflate=1.18
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libexpat=2.5.0
- libffi=3.4.2
- libflac=1.4.2
- libgcc-ng=12.2.0
- libgcrypt=1.10.1
- libgd=2.3.3
- libgdal=3.6.4
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libglib=2.76.2
- libgomp=12.2.0
- libgoogle-cloud=2.8.0
- libgpg-error=1.46
- libgrpc=1.54.1
- libiconv=1.17
- libjpeg-turbo=2.1.5.1
- libkml=1.3.0
- liblapack=3.9.0
- liblapacke=3.9.0
- libllvm11=11.1.0
- libllvm16=16.0.3
- libmamba=1.4.2
- libmambapy=1.4.2
- libnetcdf=4.9.2
- libnghttp2=1.52.0
- libnsl=2.0.0
- libnuma=2.0.16
- libogg=1.3.4
- libopenblas=0.3.21
- libopus=1.3.1
- libpng=1.6.39
- libpq=15.2
- libprotobuf=3.21.12
- librsvg=2.56.0
- librttopo=1.1.0
- libsndfile=1.2.0
- libsodium=1.0.18
- libsolv=0.7.23
- libspatialindex=1.9.3
- libspatialite=5.0.1
- libsqlite=3.40.0
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libsystemd0=253
- libthrift=0.18.1
- libtiff=4.5.0
- libtool=2.4.7
- libutf8proc=2.8.0
- libuuid=2.38.1
- libvorbis=1.3.7
- libwebp=1.3.0
- libwebp-base=1.3.0
- libxcb=1.13
- libxkbcommon=1.5.0
- libxml2=2.10.4
- libxslt=1.1.37
- libzip=1.9.2
- libzlib=1.2.13
- linopy=0.1.5
- llvmlite=0.39.1
- locket=1.0.0
- lxml=4.9.2
- lz4=4.3.2
- lz4-c=1.9.4
- lzo=2.10
- mamba=1.4.2
- mapclassify=2.5.0
- markdown=3.4.3
- markupsafe=2.1.2
- matplotlib=3.5.2
- matplotlib-base=3.5.2
- matplotlib-inline=0.1.6
- memory_profiler=0.61.0
- mercantile=1.2.1
- metis=5.1.0
- mistune=2.0.5
- mpg123=1.31.3
- msgpack-python=1.0.5
- multipledispatch=0.6.0
- munch=2.5.0
- munkres=1.1.4
- mysql-common=8.0.32
- mysql-libs=8.0.32
- nbclassic=1.0.0
- nbclient=0.7.4
- nbconvert-core=7.3.1
- nbformat=5.8.0
- ncurses=6.3
- nest-asyncio=1.5.6
- netcdf4=1.6.3
- networkx=3.1
- nodeenv=1.7.0
- nomkl=1.0
- notebook=6.5.4
- notebook-shim=0.2.3
- nspr=4.35
- nss=3.89
- numba=0.56.4
- numexpr=2.8.4
- numpy=1.23.5
- openjdk=11.0.13
- openjpeg=2.5.0
- openpyxl=3.1.2
- openssl=3.1.0
- orc=1.8.3
- packaging=23.1
- pandas=2.0.1
- pandocfilters=1.5.0
- panel=0.14.4
- pango=1.50.14
- param=1.13.0
- parquet-cpp=1.5.1
- parso=0.8.3
- partd=1.4.0
- patsy=0.5.3
- pcre2=10.40
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.5.0
- pip=23.1.2
- pixman=0.40.0
- pkgutil-resolve-name=1.3.10
- plac=1.3.5
- platformdirs=3.5.0
- pluggy=1.0.0
- ply=3.11
- pooch=1.7.0
- poppler=23.04.0
- poppler-data=0.4.12
- postgresql=15.2
- powerplantmatching=0.5.6
- pre-commit=3.3.1
- progressbar2=4.2.0
- proj=9.2.0
- prometheus_client=0.16.0
- prompt-toolkit=3.0.38
- prompt_toolkit=3.0.38
- protobuf=4.21.12
- psutil=5.9.5
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulp=2.7.0
- pulseaudio-client=16.1
- pure_eval=0.2.2
- py-cpuinfo=9.0.0
- pyarrow=11.0.0
- pybind11-abi=4
- pycosat=0.6.4
- pycountry=22.3.5
- pycparser=2.21
- pyct=0.4.6
- pyct-core=0.4.6
- pydoe2=1.3.0
- pygments=2.15.1
- pyomo=6.5.0
- pyopenssl=23.1.1
- pyparsing=3.0.9
- pyproj=3.5.0
- pypsa=0.22.1
- pyqt=5.15.7
- pyqt5-sip=12.11.0
- pyrsistent=0.19.3
- pyshp=2.3.1
- pysocks=1.7.1
- pytables=3.8.0
- pytest=7.3.1
- python=3.10.10
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.3
- python-json-logger=2.0.7
- python-tzdata=2023.3
- python-utils=3.5.2
- python_abi=3.10
- pytz=2023.3
- pyviz_comms=2.2.1
- pyyaml=6.0
- pyzmq=25.0.2
- qt-main=5.15.8
- rasterio=1.3.6
- re2=2023.02.02
- readline=8.2
- reproc=14.2.4
- reproc-cpp=14.2.4
- requests=2.29.0
- reretry=0.11.8
- reverse-geocode=1.4.1
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rioxarray=0.14.1
- rtree=1.0.1
- ruamel.yaml=0.17.24
- ruamel.yaml.clib=0.2.7
- s2n=1.3.42
- scikit-learn=1.2.2
- scipy=1.10.1
- seaborn=0.12.2
- seaborn-base=0.12.2
- send2trash=1.8.2
- setuptools=67.7.2
- shapely=2.0.1
- sip=6.7.9
- six=1.16.0
- smart_open=6.3.0
- smmap=3.0.5
- snakemake-minimal=7.25.3
- snappy=1.1.10
- sniffio=1.3.0
- snuggs=1.4.7
- sortedcontainers=2.4.0
- soupsieve=2.3.2.post1
- sqlite=3.40.0
- stack_data=0.6.2
- statsmodels=0.14.0
- stopit=1.1.2
- tabulate=0.9.0
- tblib=1.7.0
- terminado=0.17.1
- threadpoolctl=3.1.0
- throttler=1.2.1
- tiledb=2.13.2
- tinycss2=1.2.1
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- toolz=0.12.0
- toposort=1.10
- tornado=6.3
- tqdm=4.65.0
- traitlets=5.9.0
- typing-extensions=4.5.0
- typing_extensions=4.5.0
- tzcode=2023c
- tzdata=2023c
- ucx=1.14.0
- ukkonen=1.0.1
- unicodedata2=15.0.0
- unidecode=1.3.6
- urllib3=1.26.15
- virtualenv=20.23.0
- wcwidth=0.2.6
- webencodings=0.5.1
- websocket-client=1.5.1
- wheel=0.40.0
- wrapt=1.15.0
- xarray=2023.4.2
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xerces-c=3.2.4
- xkeyboard-config=2.38
- xlrd=2.0.1
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.8.4
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.10
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xf86vidmodeproto=2.3.1
- xorg-xproto=7.0.31
- xyzservices=2023.2.0
- xz=5.2.6
- y-py=0.5.9
- yaml=0.2.5
- yaml-cpp=0.7.0
- ypy-websocket=0.8.2
- yte=1.5.1
- zeromq=4.3.4
- zict=3.0.0
- zipp=3.15.0
- zlib=1.2.13
- zlib-ng=2.0.7
- zstandard=0.19.0
- zstd=1.5.2
- pip:
  - chaospy==4.3.12
  - countrycode==0.2
  - googledrivedownloader==0.4
  - highspy==1.5.0.dev0
  - install-jdk==1.0.4
  - numpoly==1.2.7
  - pybind11==2.10.4
  - tsam==2.2.2
  - vresutils==0.3.2.dev11+g150c1be
prefix: /home/max/anaconda3/envs/pypsa-earth
