# SPDX-FileCopyrightText: PyPSA-ASEAN, PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.6.0
foresight: myopic

run:
  name: base-asean # use this to keep track of runs with different settings
  sector_name: base-asean-sector
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
                        # Note: value false requires build_cutout to be enabled

results_dir: results/
summary_dir: results/

scenario:
  clusters: [300]
  opts: [Co2L-3h]
  planning_horizons: # investment years for myopic and perfect; or costs year for overnight
  - 2020
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050
  sopts:
  - "144h"
  demand:
  - "BAU"

countries: [BN, KH, ID, LA, MM, MY, PH, SG, TH, TL, VN]

enable:
  retrieve_databundle: false #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: false
  retrieve_cost_data: true # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: false # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: false # If True, then an exclusion raster will be build
  build_cutout: false

build_shape_options:
  simplify_gadm: false

electricity:
  base_network: osm-plus-prebuilt
  base_network_version: 0.1

transmission_projects:
  enable: true
  include:
    ID_SuperGrid: true
    AIMS: true
  skip: []
  status:
  - in_planning
  - under_construction
  - existing
  - under_consideration
  new_link_capacity: keep #keep or zero

costs:
  append_cost_data: true
  regional_factor: true

sector:
  land_transport_fuel_cell_share:
    BAU_2020: 0.00
    BAU_2025: 0.00
    BAU_2030: 0.00
    BAU_2035: 0.00
    BAU_2040: 0.00
    BAU_2045: 0.00
    BAU_2050: 0.00
  land_transport_electric_share:
    BAU_2020: 0.00
    BAU_2025: 0.00
    BAU_2030: 0.00
    BAU_2035: 0.00
    BAU_2040: 0.00
    BAU_2045: 0.00
    BAU_2050: 0.00
  shipping_hydrogen_share:
    BAU_2020: 0.00
    BAU_2025: 0.00
    BAU_2030: 0.00
    BAU_2035: 0.00
    BAU_2040: 0.00
    BAU_2045: 0.00
    BAU_2050: 0.00
