name: CI-linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * TUE"

env:
  CACHE_NUMBER: 1  # Change this value to manually reset the environment cache

jobs:
  build:
    strategy:
      fail-fast: false  # don't break CI for ubuntu if windows fails before
      matrix:
        include:
          # Matrix required to handle environment caching with Mambaforge
        - os: ubuntu-latest
          label: ubuntu-latest
          prefix: /usr/share/miniconda3/envs/pypsa-earth

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: pypsa-earth
        use-mamba: true

    - name: Create environment cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles('envs/environment.yaml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}

    - name: Update environment due to outdated or unavailable cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: mamba env update -n pypsa-earth -f envs/environment.yaml

    - name: Conda list
      run: |
        conda list

    - name: Create test configs
      run: |
        snakemake --cores all build_test_configs

    - name: Test tutorial workflow
      run: |
        cp test/tmp/config.tutorial_noprogress_tmp.yaml config.yaml
        snakemake --cores all solve_all_networks --forceall

    - name: Test custom workflow
      run: |
        mkdir -p configs/scenarios
        cp test/config.custom.yaml configs/scenarios/config.custom.yaml
        snakemake --cores 1 run_all_scenarios --forceall

    - name: Test monte-carlo workflow
      run: |
        cp test/tmp/config.monte_carlo_tmp.yaml config.yaml
        snakemake --cores all solve_all_networks_monte --forceall

    - name: Test landlock workflow
      run: |
        cp test/tmp/config.landlock_tmp.yaml config.yaml
        snakemake --cores all solve_all_networks --forceall

      # - name: Test plotting and summaries
      #   run: |
      #     snakemake --cores all plot_all_p_nom
      #     snakemake --cores all plot_all_summaries
      #     snakemake --cores all make_all_summaries
      #     rm -rf resources/*.nc resources/*.geojson resources/*.h5 networks results
