name: CI-mac

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 5 * * TUE"

env:
  CACHE_NUMBER: 1  # Change this value to manually reset the environment cache

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: macos-latest
          label: macos-latest
          prefix: /Users/runner/miniconda3/envs/pypsa-earth

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    # - name: Add solver to environment
    #   run: |
    #     echo -e "- glpk\n- ipopt<3.13.3" >> envs/environment.yaml

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: pypsa-earth
        use-mamba: true

    - name: Create environment cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ matrix.prefix }}
        key: ${{ matrix.label }}-conda-${{ hashFiles('envs/environment.yaml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}

    - name: Update environment due to outdated or unavailable cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: mamba env update -n pypsa-earth -f envs/environment.yaml

    - name: Conda list
      run: |
        conda list

    - name: Create test configs
      run: |
        snakemake --cores all build_test_configs

    - name: Test tutorial workflow
      run: |
        cp test/tmp/config.tutorial_noprogress_tmp.yaml config.yaml
        snakemake --cores all solve_all_networks

      # - name: Test plotting and summaries
      #   run: |
      #     snakemake --cores all plot_all_p_nom
      #     snakemake --cores all plot_all_summaries
      #     snakemake --cores all make_all_summaries
      #     rm -rf resources/*.nc resources/*.geojson resources/*.h5 networks results
